apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: nginx
    type: frontend
spec:
  template:
    metadata:
      name: nginx
      labels: 
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 3